#!/bin/bash

set -e

cd "$(dirname "$0")/.."

echo "==> Installing gem dependencies…"
bundle check || {
  bundle install --binstubs bin --path vendor/gems && bundle config set path 'vendor/gems' && bundle binstubs bin
}

echo "==> Installing node dependencies…"
npm install
